services:
  - type: web
    name: mitron-site2-tree
    env: node
    buildCommand: npm install
    startCommand: node backend/index.js
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
